dist: xenial
addons:
  chrome: stable
language: node_js
install:
- npm ci
- npm run webdriver:update
cache:
  directories:
  - node_modules
env:
  global:
  - secure: rRSiYNv+h6E1PpYKtocgOszBfwgYkhvinSTTsRf+hhDdGV3C/wkfBG8RVw0wDKLlnpci6XB5bV2uw0maAQZVH7dG1jhw05IX6/jroDgAaRORSfZDvbom/IT3yC+lRf0vzFq+K/Veql70lULCxtZTlbWFKQ2jmI8l58LiaPrcD+Kpa3ugrQrAJa4XpSveThMm2L6vQjmJThj56w2swRL0Cv5/WFAYeQeNSf+K8O0/OUODJqFzYZuIJv1BB0jqZjSK6mEqv+4r/oK6yWBZrr9SWcEN2X+TDSFhmXJu4e1LHoF2dsPq5Y1/Lb/uYnNJX4lczkoA6+fwiB5JPfLc5hrsrJ8P8QNWF5t2oDL9PqJMrv+NBRJJ+NL9/zN7bByD1VQnyib0+DIueYk53sYg4sH3CGHkZhPEwxe4slKAdCg8qd32td6lZSt39m4wmjk4qbi7BTOQNh49I7XEK0+zMBnUO1Ii3za5pZDCzq7uu039CwjiyEMMg3qP3th87lPCFGThyvyMFcPz/jQ8ANWDwTibCxhH7fVKCl+exO4ky18nic5jxSH4Jh0wfOxqa/dLLtpr+wk4T9gkKyekZ0pGjKXxluSY5iubLfxH/o3+y2DutxRoq25Q6xPIYkrVn/wD4aGny+U1z6CfcslYTkiheyWK8Cj9lj/bagx8XvhofRXcAHw=
  - secure: vcb6SHwpRDe1WuOcgRsDP43Mm4p1ppbbE8aKdp0m3lNLlsY/zk5oyoPfAjrJZgt0Ci+F+IUSmR2kujwRmYOj6ll3i6Uk5YYvoaNEDXsXVfzKLjF+UnmxKmtR6ApCM/50hkd9I76WnRlZzbAwa49zeeToUzQ7vS7X9Utd1Plf9nj23pTHLq8e98/HRI0uzJGKqsUxjP4XjCb1jTsnDk91kRUuiEo6sK3nkjFVbSnWTGW8r7HQy30CfI4HomStuC0BSts8A6GE7dZxDbJUYX6w8Z59u0VUDef6ZK8gAT74UqIEjmDk5I5/8WJLrIVlFxOCAuz9E5Jaiyhx+/KsJWyWxgyMqnKWPUbzH0aW6ciyM046EkAl6Ai8L18WjXyFw7XTv3PWJIZUMvcsVp4tUe2DSJd1c5XZLZf2C+p+tv1KQJ8FCqVZTimeyDG4bPMKuNSWGPDPpLT+vvyJtxnEZP4p01WiI9oDF+P7ShPs0ckQYljiyKIb3Af0hbpQjtNoFRkU6sGl0RR6jwWhfawSjIQQ5Ucfw1758/xtf7FRI32vt9Bvsyq6xvVKOwTg+nSRDmZptb+zqatBVNLiJfxFf0Pg+fc0nQgTdMFvCjmzYzY9Y1L/mGyAG9SAXIFzP+MlDlerexhZ52cjc++Lmnd6jvw94qmsf36vtn2naxCWMbnKIkQ=
